### ISSUE TITLE
custom form/action handling should implement sesskey checks

### ISSUE THREAD

**Issue by danmarsden** [OpenSesame/moodle-tool_opensesame#6]
https://github.com/OpenSesame/moodle-tool_opensesame/blob/main/autoconfigaicc.php#L43

ideally you should be checking sesskey there..

**Comment by FeliciaWilkes** [comment]
Thank you for this comment. Can you provide me an example of how I would implement this inside of an external page. We are not logging in as a particular user to perform the implementation of this integration.

**Comment by danmarsden** [comment]
Hi @FeliciaWilkes - the autoconfigacc.php provides it's own custom action handling code.

see this moodledocs page for what I am looking for in there:
https://moodledev.io/general/development/policies/security/crosssite-request-forgery#what-you-need-to-do-in-your-code

the $OUTPUT->confirm() api already includes the sesskey in the form that is presented to the user, so you just need to add a require_sesskey() call in the $action === 'confirm' part before it triggers your configuration process.
